version: '3'
services:
  instagram-api-proxy:
    build: server
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
    environment:
      NODE_ENV: 'development'
      SERVER_PORT: '5000'
    command: [
      'node_modules/.bin/nodemon',
      '--ignore',
      'dist/',
      '--ext',
      'ts,js',
      '--exec',
      'npm start'
    ]
  omni-stagram:
    image: node:alpine
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_ENV: 'development'
    command: [
      'npm',
      'start'
    ]
